{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default node_name=$node.name node_url=$node.url_alias}
<h3>{if $node_url}<a href={$node_url|ezurl}>{/if}{$node_name|wash}{if $node_url}</a>{/if}{/default}</h3>
<p class="author">{$node.object.owner.name|wash}</p>
{foreach array( 'short_description', 'description' ) as $attribute}
    {if and( is_set( $node.data_map[$attribute] ), $node.data_map[$attribute].has_content )}
        {attribute_view_gui attribute=$node.data_map[$attribute]}
        {break}
    {/if}
{/foreach}
